/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData cement_works = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doors = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData roofing = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData painting = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ceiling = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flooring = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plastering = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electrical = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plumbing = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData architectural = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData structural = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eandp = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rateofworkers = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manpowerdistribution = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData productivityrate = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData additionalmanp = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
